services:
  blocksyncer:
    build:
      dockerfile: Dockerfile
    ports:
      - "6180:8000"
    restart: always
    environment:
      LISTEN: 0.0.0.0:8000
      ENV: dev
      IS_TESTNET:
    labels:
      - "name=blocksyncer"
    logging:
      driver: "json-file"
      options:
        labels: "name"
